import 'package:flutter/material.dart';
import '../models/tool_item.dart';

class ToolsConfig {
  static const List<ToolCategory> categories = [
    ToolCategory(
      id: 'regex',
      name: 'Regex Tools',
      icon: Icons.auto_fix_high_rounded,
      tools: [
        ToolItem(
          id: 'regex_builder',
          name: 'Regex Builder',
          description: 'Build, test, and debug regular expressions',
          icon: Icons.auto_fix_high_rounded,
          iconColor: Color(0xFF6C63FF),
          route: '/regex-builder',
          tags: ['regex', 'pattern', 'match', 'test'],
        ),
        ToolItem(
          id: 'regex_samples',
          name: 'Regex Samples',
          description: '30+ ready-to-use patterns with test data',
          icon: Icons.collections_bookmark_rounded,
          iconColor: Color(0xFF5C6BC0),
          route: '/regex-samples',
          tags: ['regex', 'examples', 'patterns', 'library'],
        ),
        ToolItem(
          id: 'regex_cheatsheet',
          name: 'Regex Cheat Sheet',
          description: 'Interactive regex syntax reference',
          icon: Icons.menu_book_rounded,
          iconColor: Color(0xFF3949AB),
          route: '/regex-cheatsheet',
          tags: ['regex', 'reference', 'cheatsheet', 'syntax', 'guide'],
        ),
      ],
    ),
    ToolCategory(
      id: 'encoders',
      name: 'Encoders & Decoders',
      icon: Icons.lock_outline_rounded,
      tools: [
        ToolItem(
          id: 'base64',
          name: 'Base64',
          description: 'Encode and decode Base64 strings',
          icon: Icons.lock_outline_rounded,
          iconColor: Color(0xFF26A69A),
          route: '/base64',
          tags: ['base64', 'encode', 'decode'],
        ),
        ToolItem(
          id: 'url_encoder',
          name: 'URL Encoder',
          description: 'Encode and decode URL components',
          icon: Icons.link_rounded,
          iconColor: Color(0xFF42A5F5),
          route: '/url-encoder',
          tags: ['url', 'encode', 'decode', 'uri'],
        ),
        ToolItem(
          id: 'jwt_decoder',
          name: 'JWT Decoder',
          description: 'Decode and verify JWT tokens',
          icon: Icons.vpn_key_rounded,
          iconColor: Color(0xFFFF7043),
          route: '/jwt-decoder',
          tags: ['jwt', 'token', 'auth', 'decode'],
        ),
        ToolItem(
          id: 'html_entity',
          name: 'HTML Entity',
          description: 'Encode/decode HTML entities',
          icon: Icons.html_rounded,
          iconColor: Color(0xFFE65100),
          route: '/html-entity',
          tags: ['html', 'entity', 'encode', 'decode', 'xss'],
        ),
        ToolItem(
          id: 'string_escape',
          name: 'String Escape',
          description: 'Escape strings for various formats',
          icon: Icons.format_quote_rounded,
          iconColor: Color(0xFF6A1B9A),
          route: '/string-escape',
          tags: ['escape', 'unescape', 'string', 'sql', 'regex', 'json'],
        ),
      ],
    ),
    ToolCategory(
      id: 'formatters',
      name: 'Formatters',
      icon: Icons.code_rounded,
      tools: [
        ToolItem(
          id: 'json_formatter',
          name: 'JSON Formatter',
          description: 'Format, validate, and minify JSON',
          icon: Icons.data_object_rounded,
          iconColor: Color(0xFFFF9800),
          route: '/json-formatter',
          tags: ['json', 'format', 'validate', 'minify'],
        ),
        ToolItem(
          id: 'data_converter',
          name: 'Data Converter',
          description: 'Convert between JSON, CSV, YAML',
          icon: Icons.transform_rounded,
          iconColor: Color(0xFF00ACC1),
          route: '/data-converter',
          tags: ['csv', 'json', 'yaml', 'convert', 'data'],
        ),
        ToolItem(
          id: 'code_beautifier',
          name: 'Code Beautifier',
          description: 'Beautify or minify code',
          icon: Icons.auto_fix_high_rounded,
          iconColor: Color(0xFF8E24AA),
          route: '/code-beautifier',
          tags: ['beautify', 'minify', 'format', 'code', 'js', 'css', 'html'],
        ),
        ToolItem(
          id: 'sql_formatter',
          name: 'SQL Formatter',
          description: 'Format and beautify SQL queries',
          icon: Icons.storage_rounded,
          iconColor: Color(0xFF7E57C2),
          route: '/sql-formatter',
          tags: ['sql', 'format', 'database', 'query'],
        ),
        ToolItem(
          id: 'diff_viewer',
          name: 'Diff Viewer',
          description: 'Compare text and code side-by-side',
          icon: Icons.compare_arrows_rounded,
          iconColor: Color(0xFFEC407A),
          route: '/diff-viewer',
          tags: ['diff', 'compare', 'merge', 'changes'],
        ),
      ],
    ),
    ToolCategory(
      id: 'converters',
      name: 'Converters',
      icon: Icons.swap_horiz_rounded,
      tools: [
        ToolItem(
          id: 'color_converter',
          name: 'Color Converter',
          description: 'Convert between color formats',
          icon: Icons.palette_rounded,
          iconColor: Color(0xFFE91E63),
          route: '/color-converter',
          tags: ['color', 'hex', 'rgb', 'hsl', 'convert'],
        ),
        ToolItem(
          id: 'case_converter',
          name: 'Case Converter',
          description: 'Convert text between different cases',
          icon: Icons.text_format_rounded,
          iconColor: Color(0xFF8D6E63),
          route: '/case-converter',
          tags: ['case', 'camel', 'snake', 'kebab', 'text'],
        ),
        ToolItem(
          id: 'number_base',
          name: 'Number Base',
          description: 'Convert between binary, hex, decimal',
          icon: Icons.calculate_rounded,
          iconColor: Color(0xFF00897B),
          route: '/number-base',
          tags: ['binary', 'hex', 'decimal', 'convert'],
        ),
      ],
    ),
    ToolCategory(
      id: 'generators',
      name: 'Generators',
      icon: Icons.auto_awesome_rounded,
      tools: [
        ToolItem(
          id: 'hash_generator',
          name: 'Hash Generator',
          description: 'Generate MD5, SHA-256, SHA-512 hashes',
          icon: Icons.fingerprint_rounded,
          iconColor: Color(0xFF673AB7),
          route: '/hash-generator',
          tags: ['hash', 'md5', 'sha', 'crypto'],
        ),
        ToolItem(
          id: 'uuid_generator',
          name: 'UUID Generator',
          description: 'Generate v1 and v4 UUIDs',
          icon: Icons.key_rounded,
          iconColor: Color(0xFF66BB6A),
          route: '/uuid-generator',
          tags: ['uuid', 'guid', 'generate', 'unique'],
        ),
        ToolItem(
          id: 'lorem_ipsum',
          name: 'Lorem Ipsum',
          description: 'Generate placeholder text',
          icon: Icons.text_fields_rounded,
          iconColor: Color(0xFF8D6E63),
          route: '/lorem-ipsum',
          tags: ['lorem', 'placeholder', 'text', 'dummy'],
        ),
        ToolItem(
          id: 'data_generator',
          name: 'Data Generator',
          description: 'Generate fake test data',
          icon: Icons.dataset_rounded,
          iconColor: Color(0xFF00897B),
          route: '/data-generator',
          tags: ['faker', 'test data', 'mock', 'generate', 'random'],
        ),
        ToolItem(
          id: 'qr_generator',
          name: 'QR Code',
          description: 'Generate QR codes from text',
          icon: Icons.qr_code_rounded,
          iconColor: Color(0xFF424242),
          route: '/qr-generator',
          tags: ['qr', 'code', 'generate', 'barcode'],
        ),
        ToolItem(
          id: 'markdown_preview',
          name: 'Markdown Preview',
          description: 'Live markdown editor with preview',
          icon: Icons.article_rounded,
          iconColor: Color(0xFF607D8B),
          route: '/markdown-preview',
          tags: ['markdown', 'preview', 'editor', 'md'],
        ),
        ToolItem(
          id: 'password_generator',
          name: 'Password Generator',
          description: 'Generate secure passwords and secrets',
          icon: Icons.password_rounded,
          iconColor: Color(0xFFD32F2F),
          route: '/password-generator',
          tags: ['password', 'security', 'generator', 'secret'],
        ),
        ToolItem(
          id: 'image_tools',
          name: 'Image Tools',
          description: 'Base64, metadata, placeholders',
          icon: Icons.image_rounded,
          iconColor: Color(0xFF9C27B0),
          route: '/image-tools',
          tags: ['image', 'base64', 'metadata', 'placeholder'],
        ),
      ],
    ),
    ToolCategory(
      id: 'network',
      name: 'Network & API',
      icon: Icons.cloud_outlined,
      tools: [
        ToolItem(
          id: 'api_request',
          name: 'API Request Builder',
          description: 'Send HTTP requests and view responses',
          icon: Icons.http_rounded,
          iconColor: Color(0xFF1976D2),
          route: '/api-request',
          tags: ['api', 'http', 'rest', 'request', 'curl'],
        ),
        ToolItem(
          id: 'websocket_tester',
          name: 'WebSocket Tester',
          description: 'Test WebSocket connections in real-time',
          icon: Icons.cable_rounded,
          iconColor: Color(0xFF0288D1),
          route: '/websocket-tester',
          tags: ['websocket', 'ws', 'realtime', 'socket', 'chat'],
        ),
        ToolItem(
          id: 'network_tools',
          name: 'Network Tools',
          description: 'Subnet calculator, MAC generator, ports',
          icon: Icons.lan_rounded,
          iconColor: Color(0xFF0277BD),
          route: '/network-tools',
          tags: ['network', 'subnet', 'ip', 'cidr', 'mac', 'ports'],
        ),
      ],
    ),
    ToolCategory(
      id: 'utilities',
      name: 'Utilities',
      icon: Icons.build_rounded,
      tools: [
        ToolItem(
          id: 'text_analyzer',
          name: 'Text Analyzer',
          description: 'Analyze text statistics and readability',
          icon: Icons.analytics_outlined,
          iconColor: Color(0xFF00897B),
          route: '/text-analyzer',
          tags: ['text', 'analyze', 'statistics', 'readability', 'word count'],
        ),
        ToolItem(
          id: 'unicode_tools',
          name: 'Unicode Tools',
          description: 'ASCII table, emoji picker, char info',
          icon: Icons.text_format_rounded,
          iconColor: Color(0xFF5E35B1),
          route: '/unicode-tools',
          tags: ['unicode', 'ascii', 'emoji', 'character', 'utf8'],
        ),
        ToolItem(
          id: 'env_manager',
          name: 'Environment Manager',
          description: 'Manage .env files and configurations',
          icon: Icons.settings_applications_rounded,
          iconColor: Color(0xFF7B1FA2),
          route: '/env-manager',
          tags: ['env', 'environment', 'config', 'dotenv', 'variables'],
        ),
        ToolItem(
          id: 'encryption_tools',
          name: 'Encryption Tools',
          description: 'AES, RSA, Hash, HMAC, Bcrypt, ROT13',
          icon: Icons.enhanced_encryption_rounded,
          iconColor: Color(0xFF6A1B9A),
          route: '/encryption-tools',
          tags: ['encryption', 'aes', 'rsa', 'hash', 'hmac', 'bcrypt', 'security'],
        ),
        ToolItem(
          id: 'docker_tools',
          name: 'Docker/K8s Tools',
          description: 'Dockerfile, Compose, Kubernetes YAML',
          icon: Icons.widgets_rounded,
          iconColor: Color(0xFF0288D1),
          route: '/docker-tools',
          tags: ['docker', 'kubernetes', 'k8s', 'container', 'yaml', 'dockerfile'],
        ),
        ToolItem(
          id: 'snippet_manager',
          name: 'Snippet Manager',
          description: 'Save and organize code snippets',
          icon: Icons.code_rounded,
          iconColor: Color(0xFFD32F2F),
          route: '/snippet-manager',
          tags: ['snippet', 'code', 'save', 'organize', 'library'],
        ),
        ToolItem(
          id: 'enhanced_diff',
          name: 'Enhanced Diff & Merge',
          description: '3-way merge, patch generation, conflict resolution',
          icon: Icons.compare_arrows_rounded,
          iconColor: Color(0xFFE64A19),
          route: '/enhanced-diff',
          tags: ['diff', 'merge', 'patch', 'conflict', 'compare'],
        ),
        ToolItem(
          id: 'ssl_tools',
          name: 'SSL/Certificate Tools',
          description: 'Certificate decoder, CSR generator, SSL info',
          icon: Icons.security_rounded,
          iconColor: Color(0xFF558B2F),
          route: '/ssl-tools',
          tags: ['ssl', 'certificate', 'csr', 'tls', 'security', 'pem'],
        ),
        ToolItem(
          id: 'webhook_tester',
          name: 'Webhook Tester',
          description: 'Simulate and inspect webhook requests',
          icon: Icons.webhook_rounded,
          iconColor: Color(0xFF00897B),
          route: '/webhook-tester',
          tags: ['webhook', 'http', 'request', 'inspector', 'api'],
        ),
        ToolItem(
          id: 'git_tools',
          name: 'Git Tools',
          description: 'Gitignore, commits, branches, versions',
          icon: Icons.source_rounded,
          iconColor: Color(0xFFF4511E),
          route: '/git-tools',
          tags: ['git', 'gitignore', 'commit', 'branch', 'version'],
        ),
        ToolItem(
          id: 'timestamp',
          name: 'Timestamp Converter',
          description: 'Convert Unix timestamps and dates',
          icon: Icons.schedule_rounded,
          iconColor: Color(0xFFF44336),
          route: '/timestamp',
          tags: ['timestamp', 'unix', 'date', 'time'],
        ),
        ToolItem(
          id: 'cron_builder',
          name: 'Cron Expression',
          description: 'Build and test cron expressions',
          icon: Icons.event_repeat_rounded,
          iconColor: Color(0xFF00ACC1),
          route: '/cron-builder',
          tags: ['cron', 'schedule', 'expression', 'timer'],
        ),
        ToolItem(
          id: 'deeplink_tester',
          name: 'Deep Link Tester',
          description: 'Test deep links, URL schemes, universal/app links',
          icon: Icons.open_in_browser_rounded,
          iconColor: Color(0xFF1976D2),
          route: '/deeplink-tester',
          tags: ['deeplink', 'url', 'scheme', 'universal', 'applink', 'mobile'],
        ),
      ],
    ),
  ];

  static List<ToolItem> get allTools {
    return categories.expand((cat) => cat.tools).toList();
  }

  static ToolItem? getToolById(String id) {
    try {
      return allTools.firstWhere((tool) => tool.id == id);
    } catch (_) {
      return null;
    }
  }

  static ToolItem? getToolByRoute(String route) {
    try {
      return allTools.firstWhere((tool) => tool.route == route);
    } catch (_) {
      return null;
    }
  }
}
